### ISSUE TITLE
脚本除了在左下角点击, 并没有做其他事

### ISSUE THREAD

**Issue by godxqi** [kyokakawaii/DoroHelper#10]
在看板娘页面启动脚本后, 左下角有出现点击, 但也只是出现了点击, 并没有后续的动作
尝试了全屏幕模式和窗口模式, 都是一样的现象

**Comment by kyokakawaii** [comment]
游戏设置和我的一样吗？
如果方便的话把整个看板娘页面截图发一下（最好不要图片压缩）。

**Comment by godxqi** [comment]
找到原因了, 是开了windows的HDR显示, 关上就行了.
系统版本Windows 11 Version 23H2.

**Comment by kyokakawaii** [comment]
感谢提供信息
