### ISSUE TITLE
问一下大佬，这个助手是基于视觉识别的吗

### ISSUE THREAD

**Issue by Tsgumi** [kyokakawaii/DoroHelper#11]
主要还是怕封号，如果是视觉的话应该没啥问题，膜拜大佬，找了很多助手，这个是用着最舒服的

**Comment by kyokakawaii** [comment]
是的，识别特征像素。所以对游戏画质设置有要求。

**Comment by Tsgumi** [comment]
> 是的，识别特征像素。所以对游戏画质设置有要求。

tql
