### ISSUE TITLE
在点开好友窗口的时候会误触到pass

### ISSUE THREAD

**Issue by Sibao11** [kyokakawaii/DoroHelper#12]
![微信截图_20240924032147](https://github.com/user-attachments/assets/afa66e38-f219-45f4-8d17-105ca594befc)
其余流程一切正常，我手动关掉pass点开好友面板会继续流程。我的设置
![image](https://github.com/user-attachments/assets/17b689db-04bb-4151-9ea3-23252fb7c8d9)
doroHelp版本是v0.1.10

**Comment by kyokakawaii** [comment]
把游戏窗口尽量拉大可以避免出现这个问题
点这个位置是为了在有无紫色任务条时都能点到好友按钮
