### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by 2521538205** [kyokakawaii/DoroHelper#13]
1.付费商城领钻貌似是固定点位的，如果收菜的时候触发等级礼包或者新人礼包买过了就会卡死。希望付费商城可以搞一下识别
2.多个号挨个挂有点不方便，能在做完一个号之后识别另一个多开的nikke然后切过去做日常就再好不过了
最后还是感谢大佬做出来脚本把我从妮姬的日常里解放出来(

**Comment by kyokakawaii** [comment]
收到，我研究一下

**Comment by kyokakawaii** [comment]
1. 这个普通礼包的界面方便截图给我看一下吗？因为我没买新人礼包，所以不知道买了以后UI会变成什么样。

![QQ20240929-112552](https://github.com/user-attachments/assets/3a0f5444-b7ec-44b8-b74b-7152b137fc80)

2. 没用过多开。是所有的进程都叫nikke.exe吗？最好把任务管理器里和nikke有关的截图发一下。
![image](https://github.com/user-attachments/assets/60fd1615-79a7-40e1-9e0c-7313c1d83159)

**Comment by 2521538205** [comment]
买过就没有新人特别优惠了
![图片](https://github.com/user-attachments/assets/c846cd9d-2b4d-4f0f-ba2f-abc1b80b05ec)
然后这里是双开的管理器截图
![图片](https://github.com/user-attachments/assets/87b2c3e6-b515-4e5d-b702-2c8f9cc12ba1)

**Comment by kyokakawaii** [comment]
应该可以了，更新到最新版本试一下

**Comment by 2521538205** [comment]
今天试了一下，没有问题了  感谢！
![MVERXK@V5(M95EP66SC SPL](https://github.com/user-attachments/assets/32652c9b-d920-4b2d-b31d-bb087c59c173)
