### ISSUE TITLE
大佬好！反映个10月3日出现的免费钻石点击错误的问题

### ISSUE THREAD

**Issue by jaydenxzd** [kyokakawaii/DoroHelper#14]
问题：本该点击免费钻石的“普遍礼包”的标签页领取免费钻石，但点了第2个“衣架图标”的“时装商店”标签页里打开了常驻皮肤页面。
原因：是否是因为今天活动结束，导致付费商店的标签页位置变更导致的？（第1标签页消失，第2、3标签页变第1、2标签页？记不清活动礼包是否加了标签页，但应该是这种情况）

其他建议：大佬是否可以在最后添加个每日任务（和季卡）的奖励领取功能，另外是否考虑建个QQ群，谢谢大佬！

**Comment by kyokakawaii** [comment]
等12点活动开放后，礼包上架就行了。
确实是礼包标签页没了导致的。这次活动是中午12点开，而且也没有维护。以前似乎没出现过这种情况，不知道以后会不会再次出现。

每日任务奖励领取不考虑加。季卡没买过，不知道奖励是怎么领取的，ui方便截图发一下吗？

QQ群不打算建了。

**Comment by jaydenxzd** [comment]
![1](https://github.com/user-attachments/assets/fc4dd6bb-8ff5-4d4b-b423-fc65d59d6a62)
![2](https://github.com/user-attachments/assets/870ebba3-d10f-4f77-800c-165bd1470ba2)
zhe
![3](https://github.com/user-attachments/assets/de3c4c19-9a0d-4001-bbc7-d23de1ccf25f)
zheqi
![4](https://github.com/user-attachments/assets/a942ba6b-b96d-4870-ace2-4801fff55f9c)
这期我也没买，但买不买界面差别不大，供大佬参考
