### ISSUE TITLE
DORO运行抛ERROR

### ISSUE THREAD

**Issue by dierfeichai2** [kyokakawaii/DoroHelper#17]
DORO版本：v0.1.15
错误描述：以管理员身份启动DORO后窗口报错，显示如下
![image](https://github.com/user-attachments/assets/f04ba35e-2a51-4ef6-bbe5-491afd0d6aa2)

请帮帮DORO

**Comment by kyokakawaii** [comment]
网络问题。把自动检测更新关了应该就行了。

**Comment by kyokakawaii** [comment]
如果进不了脚本的话，找到同目录下settings.ini，用记事本打开，里面有一行
`isCheckedAutoCheckUpdate=1`
改成
`isCheckedAutoCheckUpdate=0`
然后保存退出就行了

**Comment by dierfeichai2** [comment]
> 如果进不了脚本的话，找到同目录下settings.ini，用记事本打开，里面有一行 `isCheckedAutoCheckUpdate=1` 改成 `isCheckedAutoCheckUpdate=0` 然后保存退出就行了

十分感谢，DORO已经恢复正常工作！
