### ISSUE TITLE
2K全屏幕一直点左下角

### ISSUE THREAD

**Issue by Demo-bx** [kyokakawaii/DoroHelper#19]
两台设备都用过该脚本，1080p分辨率的无论视窗还是全屏幕都能成功运行。但是2k分辨率的只要视窗模式能正常运行，全屏幕时一直点左下角。画质已开最高，winHDR关闭。

**Comment by kyokakawaii** [comment]
一直点左下角是因为没有识别到主页的巴拉图标。
建议用window spy之类的工具看看这个巴拉图标左下角的橙色，在窗口模式和在全屏模式下是不是差不多的颜色。
![40AC10C6A4B25523ECDD08A80DB383EE](https://github.com/user-attachments/assets/0d414d0b-d029-49f5-87b4-5a2d7cf3ed6a)

**Comment by Demo-bx** [comment]
![屏幕截图 2024-11-13 122237](https://github.com/user-attachments/assets/0b50692b-d817-4ac4-8e9b-ace85f581534)
![屏幕截图 2024-11-13 122338](https://github.com/user-attachments/assets/2c614ca0-c787-4dc3-9a0c-e8314d3999bd)
基本都在F8A325左右

**Comment by Demo-bx** [comment]
为啥你的screen window client参数一样

**Comment by kyokakawaii** [comment]
> 为啥你的screen window client参数一样

因为我开的全屏模式。而且你下面那个出现负数了，说明nikke窗口不在最前面，得点一下把它激活了

颜色倒是没问题。第一个图是窗口模式，第二个图是全屏模式吗？

**Comment by Demo-bx** [comment]
> > 为啥你的screen window client参数一样
> 
> 因为我开的全屏模式。而且你下面那个出现负数了，说明nikke窗口不在最前面，得点一下把它激活了
> 
> 颜色倒是没问题。第一个图是窗口模式，第二个图是全屏模式吗？

是的，第一个窗口第二个全屏幕。我又截了一次，激活窗口了
图一窗口
![屏幕截图 2024-11-13 133342](https://github.com/user-attachments/assets/6b6a2e91-bb44-4915-a893-2bf65d685ab0)
图二全屏
![屏幕截图 2024-11-13 133427](https://github.com/user-attachments/assets/c4688eee-2e9d-4eb3-94be-8392f9a52c5a)

**Comment by Demo-bx** [comment]
我觉得你可以设计在脚本运行开始时，将脚本识别的第一幅画面保存为临时文件，方便用户排查。但我不知道AHK脚本有没有这个功能

**Comment by kyokakawaii** [comment]
不是，这nikke同长宽比下的元素布局怎么还不一样的？
我这里开2k全屏，(45,334)这个坐标已经在图标外面了。
你的方便全屏截图看一下吗？
![image](https://github.com/user-attachments/assets/38c441d3-cb50-40ee-8f7c-90c6cced0fec)

**Comment by kyokakawaii** [comment]
你的2k分辨率是2560*1440吗

**Comment by Demo-bx** [comment]
OK，问题解决了，我是2560x1600的，分辨率改一下就能运行了。hhh我以为我是2K原来是2.5K没注意
