### ISSUE TITLE
无法记住配置更改（也可能只是ui显示问题）

### ISSUE THREAD

**Issue by mxia9416** [kyokakawaii/DoroHelper#21]
0.1.16版本中，修改设置后下一次启动记不住之前的设置，查看了配置文件发现设置是改了的（如果没理解错），但是没反映到app上，如图，自动检查更新已经是1，但是app里没有被勾选：
![image](https://github.com/user-attachments/assets/ef48ff4d-8067-4abd-a22e-9bf44abb6719)

**Comment by kyokakawaii** [comment]
感谢反馈，已经修复并换源

**Comment by mxia9416** [comment]
大佬，我想在你的代码的基础上，写一个别的游戏的日常脚本，如果能做出来会写明来源，请问能否得到你的授权？~

**Comment by kyokakawaii** [comment]
没问题的。但我十分不建议用我这个做基础，因为本来想着只是自用一下，代码写得非常不规范，逻辑也没有规划好，惭愧惭愧。想做脚本建议看看MAA([https://github.com/MaaXYZ/MaaFramework](url))，这个方便新人上手；或者研究一下alas的代码([https://github.com/LmeSzinc/AzurLaneAutoScript](url))
