### ISSUE TITLE
哥 请问这是什么原因啊

### ISSUE THREAD

**Issue by QW111854** [kyokakawaii/DoroHelper#6]
不知道为什么说我窗口找不到
![QQ图片20240820221512](https://github.com/user-attachments/assets/7dee8b7c-0f1c-49f1-be7d-04b45124bafc)

**Comment by kyokakawaii** [comment]
图上看不出来，你的游戏窗口名字是NIKKE吗？

**Comment by kyokakawaii** [comment]
已增加港澳台客户端适配

**Comment by QW111854** [comment]
好勒哥 祝老哥身体健康 万事如意
