### ISSUE TITLE
希望增加自动打异常拦截的功能

### ISSUE THREAD

**Issue by GENDORYang** [kyokakawaii/DoroHelper#8]
异常拦截随便打都比特殊拦截奖励多，但是异常拦截打完全程也要3分钟

希望能增加一个异常拦截开关，可自选5个异常拦截boss
勾选后进入拦截战界面脚本会打选中的boss

萌新不勾选异常拦截选项则照旧在拦截战界面停留

**Comment by kyokakawaii** [comment]
收到

**Comment by zzb-yy** [comment]
建议5个异常拦截对应下面的1-5个队伍。

**Comment by kyokakawaii** [comment]
已增加，点击更新按钮即可

**Comment by zzb-yy** [comment]
有个小问题，更新后软件能不能关闭原版本自动覆盖后再打开？而不是在目录新增新版本

**Comment by kyokakawaii** [comment]
> 有个小问题，更新后软件能不能关闭原版本自动覆盖后再打开？而不是在目录新增新版本

ok，下次更新试试
